"""add_viral_titles_to_clips

Revision ID: 6c0cf6438ae8
Revises: a3f7c9e21b04
Create Date: 2026-04-22 19:20:07.687036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c0cf6438ae8'
down_revision: Union[str, Sequence[str], None] = 'a3f7c9e21b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('viral_titles', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clips', 'viral_titles')
    # ### end Alembic commands ###
