"""add_editing_guide_to_clips

Revision ID: 5a762d37fb2d
Revises: 6c0cf6438ae8
Create Date: 2026-04-22 20:11:46.838605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a762d37fb2d'
down_revision: Union[str, Sequence[str], None] = '6c0cf6438ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('editing_guide', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clips', 'editing_guide')
    # ### end Alembic commands ###
