"""add_video_start_offset_to_tasks

Revision ID: 89b5d32c1dfb
Revises: d1ea2b34eb80
Create Date: 2026-04-08 12:02:20.083926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b5d32c1dfb'
down_revision: Union[str, Sequence[str], None] = 'd1ea2b34eb80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('video_start_offset', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'video_start_offset')
    # ### end Alembic commands ###
